In [3]:
import numpy as np

"""Exercise 1: Create a 5*2 integer array from a range between 100 to 200 such 
that the difference between each element is 10."""
result = np.arange(start=100, stop=200, step=10)
result = result.reshape(5, 2)
print(f"Numpy Exercise 1 result:\n{result}")


Numpy Exercise 1 result:
[[100 110]
 [120 130]
 [140 150]
 [160 170]
 [180 190]]


In [4]:
"""Exercise 2: following in the provided numpy array. return array of item in the third column from all rows."""
sample_array = np.array([[11, 22, 33], [44, 55, 66], [77, 88, 99]])
result = sample_array[0:, 2]
print(f"Numpy Exercise 2 result:\nsample Array:\n{sample_array}\nThird column from all rows:\n{result}")

Numpy Exercise 2 result:
sample Array:
[[11 22 33]
 [44 55 66]
 [77 88 99]]
Third column from all rows:
[33 66 99]


In [6]:
"""Exercise 3: Add the following two numpy arrays and Modify a result array by calculating the square of each element"""
array_one = np.array([[5, 6, 9], [21, 18, 27]])
array_two = np.array([[15, 33, 22], [4, 7, 1]])
print(f"Numpy Exercise 3 result:\nArray 1:\n{array_one}")
print(f"Array 2:\n{array_two}")
add_array = np.add(array_one, array_two)
sqr_array = np.square(add_array)
print(f"Adding arrays:\n{add_array}\nsquare of array:\n{sqr_array}")

Numpy Exercise 3 result:
Array 1:
[[ 5  6  9]
 [21 18 27]]
Array 2:
[[15 33 22]
 [ 4  7  1]]
Adding arrays:
[[20 39 31]
 [25 25 28]]
square of array:
[[ 400 1521  961]
 [ 625  625  784]]
